/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

/**
 *
 * @author alu13257670
 */
public class ScoreBoard extends javax.swing.JPanel implements ScoreInterface {

    //private static ScoreBoard scoreBoardInstance;
    
    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        nameDataLabel.setText(ConfigData.getInstance().getPlayerName());
        scoreDataLabel.setText(Integer.toString(ConfigData.getInstance().getScore()));
    }

    public void incrementScorePoints(int newFoodPoints) {
        int currentScore = ConfigData.getInstance().getScore();
        currentScore = currentScore + newFoodPoints;
        ConfigData.getInstance().setScore(currentScore);
        scoreDataLabel.setText(Integer.toString(ConfigData.getInstance().getScore()));
    }

    public void resetScorePoints() {
        ConfigData.getInstance().setScore(0);
        scoreDataLabel.setText(Integer.toString(ConfigData.getInstance().getScore()));
    }
    
    public void setPlayerName(String playerName) {
        nameDataLabel.setText(playerName);
    }
    
    public int getCurrentScore() {
        return Integer.parseInt(scoreDataLabel.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreDataLabel = new javax.swing.JLabel();
        nameDataLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        nameLabel.setText("Name:");

        scoreLabel.setText("Score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameDataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(scoreLabel)
                .addGap(18, 18, 18)
                .addComponent(scoreDataLabel)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreDataLabel)
                        .addComponent(scoreLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameDataLabel)
                        .addComponent(nameLabel)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameDataLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel scoreDataLabel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables

}
